---
title: "YRBS_Combined"
author: "Xueqing Zhou"
date: "2022-11-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r library, message=FALSE}
## load the libraries
library(readr)
library(survey)
library(dplyr)
library(tidyverse)
library(gtsummary)
options(survey.lonely.psu="adjust")
```

```{r, message=FALSE}
## read in the data
yrbs_all <- read.csv("sadc_2019_national.csv")
```

## Data Cleaning

```{r}
## recode "" as NAs for `race7`
yrbs <- yrbs_all %>%
  mutate(across(race7, ~ifelse(. == "", NA, .)))

## subset black data and correct the outcome variable
black_data <- yrbs_all %>%
  ## filter only "Black or African American"
  filter(race7 == "Black or African American") %>%
  ## correct the outcome variable (1 - Yes, 2 - No)
  mutate(qn28 = replace(qn28, which(qn26 == 2 & qn27 == 2), 2)) %>%
  mutate(qn29 = replace(qn29, which(qn26 == 2 & qn27 == 2), 2)) %>%
  mutate(qn29 = replace(qn29, which(qn28 == 2), 2)) %>%
  mutate(qn28 = replace(qn28, which(qn29 == 1), 1)) %>%
  mutate(qn27 = replace(qn27, which(qn26 == 2), 2)) %>%
  mutate(qn28 = replace(qn28, which(qn26 == 2), 2)) %>%
  mutate(qn29 = replace(qn29, which(qn26 == 2), 2)) %>%
  mutate(qn26 = replace(qn26, which(qn27 == 1), 1)) %>%
  mutate(qn26 = replace(qn26, which(qn28 == 1), 1)) %>%
  mutate(qn26 = replace(qn26, which(qn29 == 1), 1)) %>%
  #drop_na(qn26:qn29) %>%
  ## change '2 - No' to '0 - No' for better analysis
  mutate(across(qn26:qn29, ~ ifelse(. == 2, 0, .))) %>%
  ## recode "" as NAs
  mutate(across(c(sexpart, sexid, grade, sex, age), ~ ifelse(. == "", NA, .))) %>%
  ## recode "Missing" as NAs
  mutate(across(c(q65, q66), ~ ifelse(. == "Missing", NA, .)))
```


## Survey Weighted

```{r}
# weighted design data
yrbsdes <- svydesign(id=~PSU, 
                     weight=~weight, 
                     strata=~stratum, 
                     data=black_data, 
                     nest=TRUE)

yrbsdes_all <- svydesign(id=~PSU, 
                     weight=~weight, 
                     strata=~stratum, 
                     data=yrbs_all, 
                     nest=TRUE)
```


## dropped independent variable

```{r}
## bmi dropped: 37% missing data
summary(black_data$bmi)
17073/46403
```


## Race

```{r}
## black proportion
round(prop.table(svytable(~race7, yrbsdes_all)), 3)
## NA proportion
round(prop.table(svytable(~race7, yrbsdes_all, na.action = na.pass, exclude = NULL)), 3)
```


## Combined dependent variable summarization (yes and missing proportions)

```{r}
## extract dependent variable names
qn_dependent_colnames <- black_data %>%
  select(qn26, qn27, qn28, qn29) %>%
  colnames

## create indicator
prev_indicator <- data.frame(question = rep(qn_dependent_colnames, each = 2),
                             type = c("yes", "missing"))

## create empty dataframe to store numbers
prev_data <- data.frame()

## format: keep tail 0
for (i in seq_along(qn_dependent_colnames)){
  FORMULA = as.formula(paste("~", qn_dependent_colnames[i], "+ year"))
  qn_yes <- round(prop.table(svytable(FORMULA, yrbsdes), 2)[-1, ] * 100, 3)
  qn_na <- round(prop.table(svytable(FORMULA, yrbsdes, 
                                   na.action = na.pass, exclude = NULL), 2)[3, ] * 100, 3)
  tbl <- rbind(qn_yes, qn_na)
  rownames(tbl) <- NULL
  prev_data <- rbind(prev_data, tbl)
}

## bind indicator and numbers together and add percentage sign
## *percentage sign: change column from numeric to character*
prev_tbl <- bind_cols(prev_indicator, prev_data) %>%
  mutate(across("1991":"2019", ~ paste0(.x, "%")))

prev_tbl

## total % missingness by question
bind_cols(prev_indicator, prev_data) %>%
  filter(type == "missing") %>%
  mutate(total = rowMeans(.[, 3:17]))
```


## Combined independent variable summarization

```{r}
## extract independent variable names (only qn)
qn_ind_colnames <- black_data %>%
  select(num_range("qn", 8:89), 
        -qn26, -qn27, -qn28, -qn29) %>%
  colnames()

## create indicator
ind_indicator <- data.frame(question = rep(qn_ind_colnames, each = 2),
                            type = c("yes", "missing"))

## create empty dataframe to store numbers
ind_data <- data.frame()

for (i in seq_along(qn_ind_colnames)){
  FORMULA = as.formula(paste("~", qn_ind_colnames[i], "+ year"))
  qn_yes <- round(prop.table(svytable(FORMULA, yrbsdes,
                                             na.action = na.pass), 2)[1, ] * 100, 3)
  qn_na_all <- prop.table(svytable(FORMULA, yrbsdes, 
                                   na.action = na.pass, exclude = NULL), 2)
  qn_na <- round(qn_na_all[nrow(qn_na_all), ] * 100, 3)
  
  tbl <- rbind(qn_yes, qn_na)
  rownames(tbl) <- NULL
  ind_data <- rbind(ind_data, tbl)
}

## only qn table
ind_qn_tbl <- bind_cols(ind_indicator, ind_data)


## extract independent variable names: age, sex, grade, sexid, sexpart, q65, q66
qn_other_colnames <- black_data %>%
  select(age, sex, grade, sexid, sexpart, q65, q66) %>%
  colnames()

## create empty dataframe to store numbers
ind_other <- data.frame()

for (i in seq_along(qn_other_colnames)){
  FORMULA = as.formula(paste("~", qn_other_colnames[i], "+ year"))
  
  qn_response <- round(prop.table(svytable(FORMULA, yrbsdes,
                                           na.action = na.pass), 2) * 100, 3) %>%
    as.data.frame() %>%
    pivot_wider(names_from = year, values_from = Freq) %>%
    rename(type = qn_other_colnames[i]) %>%
    mutate(question = rep(all_of(qn_other_colnames[i]), each = nrow(.)), .before = 1) %>%
    mutate(type = as.character(type))
  
  qn_na <- round(prop.table(svytable(FORMULA, yrbsdes, 
                                     na.action = na.pass, exclude = NULL), 2) * 100, 3) %>%
    as.data.frame() %>%
    pivot_wider(names_from = year, values_from = Freq) %>%
    rename(type = qn_other_colnames[i]) %>%
    mutate(question = rep(all_of(qn_other_colnames[i]), each = nrow(.)), .before = 1) %>%
    mutate(type = as.character(type)) %>%
    filter(row_number() == n()) %>%
    mutate(type = ifelse(is.na(type), "missing", type))
   
  tbl <- rbind(qn_response, qn_na)
  ind_other <- rbind(ind_other, tbl)
}

## all independent variable summarization dataframe
ind_tbl <- rbind(ind_qn_tbl, ind_other) %>%
  mutate_all(~ifelse(is.nan(.), NA, .))
  ## add percentage sign: *will change variable type*
#  mutate(across("1991":"2019", ~ ifelse(!is.na(.), paste0(.x, "%"), .x)))

## calculate overall % missingness for each variable during the years it was collected
ind_col <- ind_tbl %>% 
   select(-question, -type) %>% 
   colnames()

ind_tbl[,ind_col][ind_tbl[,ind_col] == 100.00] <- NA
ind_tbl$overall_missing <- round(rowMeans(ind_tbl[,3:17], na.rm = TRUE), 3)
ind_tbl <- ind_tbl %>% 
  mutate(overall_missing = ifelse(type != 'missing', NA, overall_missing))
ind_tbl[ind_tbl$type == "missing", 
        ind_col][is.na(ind_tbl[ind_tbl$type == "missing", ind_col])] <- 100.00

sort_all_missing <- ind_tbl %>%
  arrange(desc(overall_missing))

## drop >20% missingness, calculate complete case number (by year and total)
less_than_20 <- sort_all_missing %>%
  filter(overall_missing < 20)
less_than_20[,ind_col][less_than_20[,ind_col] == 100.00] <- NA

year_array <- as.character(unique(black_data$year))
complete <- data.frame(matrix(nrow = 1))

for (i in 1:length(year_array)){
  collected_year <- less_than_20 %>%
    select(question, type, year_array[i]) %>%
    na.omit() %>%
    select(question) %>%
    unlist() %>%
    unname()
  
  complete_num <- black_data %>%
    filter(year == year_array[i]) %>%
    select(all_of(collected_year)) %>%
    na.omit() %>%
    summarise(nrow(.))
  
  complete <- cbind(complete, complete_num)
}

complete <- complete[,-1]
colnames(complete) = year_array

complete
```


## Raw Count

```{r}
## prevalence of each year (count of each year?)
prev_by_year <- black_data %>% 
  group_by(year) %>%
  summarise(across(qn26:qn29, sum))


## prevalence vs. 4 outcome variables by year
prev_by_year %>%
  pivot_longer(qn26:qn29,
               names_to = "outcomes",
               values_to = "prevalence") %>%
  group_by(year) %>%
  ggplot(aes(outcomes, prevalence, fill = as.factor(year))) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(title = "Prevalence vs. 4 Outcome Variables by Year",
       x = "Outcome Variables",
       y = "Prevalence",
       fill = "Year")


## prevalence vs. year by 4 outcome variables
prev_by_year %>%
  pivot_longer(qn26:qn29,
               names_to = "outcomes",
               values_to = "prevalence") %>%
  group_by(outcomes) %>%
  ggplot(aes(as.factor(year), prevalence, fill = outcomes)) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(title = "Prevalence vs. Year by 4 Outcome Variables",
       x = "Year",
       y = "Prevalence",
       fill = "Outcome Variables")
```

## No correction outcome variables

```{r}
blk_data_origin <- yrbs_all %>%
  filter(race7 == "Black or African American") %>%
  drop_na(qn26:qn29) %>%
  ## change '2 - No' to '0 - No' for better analysis
  mutate(across(qn26:qn29, ~ ifelse(. == 2, 0, .)))

## prevalence of each year (count of each year?)
prev <- blk_data_origin %>% 
  group_by(year) %>%
  summarise(across(qn26:qn29, sum))

## prevalence vs. 4 outcome variables by year
prev %>%
  pivot_longer(qn26:qn29,
               names_to = "outcomes",
               values_to = "prevalence") %>%
  group_by(year) %>%
  ggplot(aes(outcomes, prevalence, fill = as.factor(year))) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(title = "Prevalence vs. 4 Outcome Variables by Year",
       x = "Outcome Variables",
       y = "Prevalence",
       fill = "Year")

## prevalence vs. year by 4 outcome variables
prev_by_year %>%
  pivot_longer(qn26:qn29,
               names_to = "outcomes",
               values_to = "prevalence") %>%
  group_by(outcomes) %>%
  ggplot(aes(as.factor(year), prevalence, fill = outcomes)) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(title = "Prevalence vs. Year by 4 Outcome Variables",
       x = "Year",
       y = "Prevalence",
       fill = "Outcome Variables")

## *should drop ppl with no answer for races*
yrbs_all %>%
  group_by(year) %>%
  mutate(total_num = n()) %>%
  filter(race7 == "Black or African American") %>%
  mutate(black_num = n()) %>%
  filter(!duplicated(year)) %>%
  select(year, total_num, black_num) %>%
  mutate(black_prop = round(black_num / total_num, 3))

table(yrbs_all$race7)
```
